site_name: fdaPDE
edit_uri : ''

theme:
    name: material
    icon:
       repo: fontawesome/brands/github
    features:
       - navigation.tabs
       - navigation.expand
       - navigation.sections
       - content.code.annotate
       - navigation.indexes
       
extra_css:
   - stylesheets/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - tables
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
   - Home: 'index.md'
   - Getting started : 'start.md'
   - Documentation:
       - Core :
           - utils :
               - ScalarField: 'core/utils/ScalarField.md'
               - DifferentiableScalarField: 'core/utils/DifferentiableScalarField.md'
               - TwiceDifferentiableScalarField: 'core/utils/TwiceDifferentiableScalarField.md'
           - OPT :
               - core/OPT/index.md
               - GridOptimizer: 'core/OPT/GridOptimizer.md'
               - NewtonOptimizer: 'core/OPT/NewtonOptimizer.md'
               - ExactNewtonOptimizer: 'core/OPT/ExactNewtonOptimizer.md'
               - GradientDescentOptimizer: 'core/OPT/GradientDescentOptimizer.md'
               - BFGS : 'core/OPT/BFGSOptimizer.md'
               - Extensions : 'core/OPT/Extensions.md'
           - MESH :
               - 'core/MESH/index.md'
               - Mesh : 'core/MESH/Mesh.md'
               - Element : 'core/MESH/Element.md'
               - Geometry : 'core/MESH/Geometry.md'
               - BruteForceSearch : 'core/MESH/BFS.md'
               - BarycentricWalkSearch : 'core/MESH/BWS.md'
               - TreeBasedSearch : 'core/MESH/TBS.md'
           - R Interface: 'R.md'

repo_url: https://github.com/fdaPDE/fdaPDE
repo_name: fdaPDE/fdaPDE